name: Python Bazel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Set up Bazel
      uses: bazelbuild/setup-bazelisk@v2

    - name: Make scripts executable
      run: |
        chmod +x scripts/lint.sh
        chmod +x scripts/format.sh

    - name: Run unit tests
      run: |
        bazel test //tests:test_math_utils //tests:test_string_utils

    - name: Run linter
      run: |
        bazel test //:lint

    - name: Run formatter
      run: |
        bazel test //:format